Tests and update
bancolombia/scaffold-clean-architecture-ex pull request #28
Opened 2023-05-10 12:40 UTC by maocq

2023-05-10 12:58 UTC, juancgalvis requested changes
Please review the single comment

2023-05-10 12:58 UTC, juancgalvis commented on priv/templates/structure/application.ex
> +    children = with_plug_server(config) ++ all_env_children() ++ env_children(:env)
env should be passed from mix.exs config

2023-05-10 13:23 UTC, santicalleg approved these changes

2023-05-10 13:25 UTC, santicalleg approved these changes

2023-05-10 13:47 UTC, juancgalvis approved these changes

2023-05-10 13:47 UTC, merged

2024-01-31 12:55 UTC, juancgalvis commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bancolombia/scaffold-clean-architecture-ex/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: